apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: commit-anal-hig-openidl-cc-aais-carriers-v11182021-1
  namespace: analytics-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: commit-anal-hig-openidl-cc-aais-carriers-v11182021-1
  chart:
    git: https://github.com/openidl-aais/openidl-aais-gitops.git
    ref: analytics_dev
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/commit_chaincode
  values:
    metadata:
      namespace: analytics-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.analytics-net:7051
      localmspid: analyticsMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.dev.analytics.internal.aaisdirect.com
      authpath: devanalytics-net-auth
      adminsecretprefix: analytics/crypto/peerOrganizations/analytics-net/users/admin
      secretpath: analytics
      orderersecretprefix: analytics/crypto/peerOrganizations/analytics-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.ordererorg.dev.openidl.aaisdirect.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.3
      name: openidl-cc-aais-carriers
      version: v11182021
      sequence: 1
      commitarguments: ''
      endorsementpolicies:  ''
      collectionconfig: |-
        WwogIHsKICAgICJuYW1lIjogImFuYWx5dGljc19oaWdfcGRjIiwKICAgICJwb2xpY3kiOiAiT1Io
        J2FuYWx5dGljc01TUC5tZW1iZXInLCAnaGlnTVNQLm1lbWJlcicpIiwKICAgICJyZXF1aXJlZFBl
        ZXJDb3VudCI6IDAsCiAgICAibWF4UGVlckNvdW50IjogMCwKICAgICJibG9ja1RvTGl2ZSI6IDAK
        ICB9Cl0KCg==
      usecollectionconfig: true
    channel:
      name: anal-hig
    endorsers:
      creator: analytics-net
      name:  analytics  
      corepeeraddress:  peer0.analytics-net.analytics.dev.analytics.aaisdirect.com:8443 
