apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-aais-anal-carr
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-aais-anal-carr
  chart:
    git: https://github.com/openidl-aais/openidl-aais-gitops
    ref: aais_dev
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: aais-net
      network:
        version 2.2.3
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.aais-net:7051
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.openidl.internal.aaisdirect.com
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: anal-carr
    orderer:
      address: orderer1.ordererorg.dev.openidl.aaisdirect.com:8443
    channeltx: |-
      Cp0DChcKFQgCGgYI5LzxiwYiCWFuYWwtY2FychKBAwr+AgoJYW5hbC1jYXJyEi4SHAoLQXBwbGlj
      YXRpb24SDRILCgdhYWlzTVNQEgAaDgoKQ29uc29ydGl1bRIAGsACEpgCCgtBcHBsaWNhdGlvbhKI
      AggBEgsKB2FhaXNNU1ASABokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIjMK
      FExpZmVjeWNsZUVuZG9yc2VtZW50EhsSEQgDEg0KC0VuZG9yc2VtZW50GgZBZG1pbnMiIgoHUmVh
      ZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJz
      GgZBZG1pbnMiIAoGQWRtaW5zEhYSDAgDEggKBkFkbWlucxoGQWRtaW5zIioKC0VuZG9yc2VtZW50
      EhsSEQgDEg0KC0VuZG9yc2VtZW50GgZBZG1pbnMqBkFkbWlucxojCgpDb25zb3J0aXVtEhUSEwoR
      T3BlbklETENvbnNvcnRpdW0=