apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-anal-aais-aais
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-anal-aais-aais
  chart:
    git: https://github.com/openidl-aais/openidl-aais-gitops
    ref: aais_dev
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.aais-net.aais.dev.openidl.aaisdirect.com:8443
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.openidl.internal.aaisdirect.com
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: anal-aais      
    orderer:
      address: orderer1.ordererorg.dev.openidl.aaisdirect.com:8443
    anchorstx: |-
      Cs0CChcKFQgCGgYI1aDxiwYiCWFuYWwtYWFpcxKxAgquAgoJYW5hbC1hYWlzEmASXgoLQXBwbGlj
      YXRpb24STwgBEksKB2FhaXNNU1ASQBoHCgNNU1ASACIKCgZBZG1pbnMSACIPCgtFbmRvcnNlbWVu
      dBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAavgESuwEKC0FwcGxpY2F0aW9uEqsBCAESpgEK
      B2FhaXNNU1ASmgEIARpOCgtBbmNob3JQZWVycxI/EjUKMwoucGVlcjAuYWFpcy1uZXQuYWFpcy5k
      ZXYub3BlbmlkbC5hYWlzZGlyZWN0LmNvbRD7QRoGQWRtaW5zGgcKA01TUBIAIgoKBkFkbWlucxIA
      Ig8KC0VuZG9yc2VtZW50EgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACoGQWRtaW5z

