apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-defaultchannel-aais
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-defaultchannel-aais
  chart:
    git: https://github.com/openidl-aais/openidl-aais-gitops
    ref: aais_dev
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.aais-net.aais.dev.openidl.aaisdirect.com:8443
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.openidl.internal.aaisdirect.com
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: defaultchannel      
    orderer:
      address: orderer1.ordererorg.dev.openidl.aaisdirect.com:8443
    anchorstx: |-
      CtcCChwKGggCGgYIu97MiwYiDmRlZmF1bHRjaGFubmVsErYCCrMCCg5kZWZhdWx0Y2hhbm5lbBJg
      El4KC0FwcGxpY2F0aW9uEk8IARJLCgdhYWlzTVNQEkAaBwoDTVNQEgAiCgoGQWRtaW5zEgAiDwoL
      RW5kb3JzZW1lbnQSACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIAGr4BErsBCgtBcHBsaWNhdGlv
      bhKrAQgBEqYBCgdhYWlzTVNQEpoBCAEaTgoLQW5jaG9yUGVlcnMSPxI1CjMKLnBlZXIwLmFhaXMt
      bmV0LmFhaXMuZGV2Lm9wZW5pZGwuYWFpc2RpcmVjdC5jb20Q+0EaBkFkbWlucxoHCgNNU1ASACIK
      CgZBZG1pbnMSACIPCgtFbmRvcnNlbWVudBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAqBkFk
      bWlucw==

