apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: commit-anal-aais-openidl-cc-aais-carriers-v2-1
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: commit-anal-aais-openidl-cc-aais-carriers-v2-1
  chart:
    git: https://github.com/openidl-aais/openidl-aais-gitops
    ref: aais_dev
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/commit_chaincode
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.aais-net:7051
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.dev.openidl.internal.aaisdirect.com
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      secretpath: aais
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.ordererorg.dev.openidl.aaisdirect.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.3
      name: openidl-cc-aais-carriers
      version: v2
      sequence: 1
      commitarguments: ''
      endorsementpolicies:  ''
      collectionconfig: |-
        WwogIHsKICAgICJuYW1lIjogImFuYWx5dGljc19hYWlzX3BkYyIsCiAgICAicG9saWN5IjogIk9S
        KCdhbmFseXRpY3NNU1AubWVtYmVyJywgJ2FhaXNNU1AubWVtYmVyJykiLAogICAgInJlcXVpcmVk
        UGVlckNvdW50IjogMCwKICAgICJtYXhQZWVyQ291bnQiOiAwLAogICAgImJsb2NrVG9MaXZlIjog
        MAogIH0sCiAgewogICAgIm5hbWUiOiAiYW5hbF9hYWlzX3BkYyIsCiAgICAicG9saWN5IjogIk9S
        KCdhbmFseXRpY3NNU1AubWVtYmVyJywgJ2FhaXNNU1AubWVtYmVyJykiLAogICAgInJlcXVpcmVk
        UGVlckNvdW50IjogMCwKICAgICJtYXhQZWVyQ291bnQiOiAwLAogICAgImJsb2NrVG9MaXZlIjog
        MAogIH0KXQoK
      usecollectionconfig: true
    channel:
      name: anal-aais
    endorsers:
      creator: aais-net
      name:  aais  
      corepeeraddress:  peer0.aais-net.aais.dev.openidl.aaisdirect.com:8443 
