apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: join-analytics-aais-aais-peer0
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: join-analytics-aais-aais-peer0
  chart:
    git: https://github.com/openidl-aais/openidl-aais-gitops
    ref: aais_dev
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.aais-net.aais.dev.openidl.aaisdirect.com:8443
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.openidl.internal.aaisdirect.com
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: analytics-aais      
    orderer:
      address: orderer1.ordererorg.dev.openidl.aaisdirect.com:8443
