apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: approve-defaultchannel-openidl-cc-default-v10251448-1
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: approve-defaultchannel-openidl-cc-default-v10251448-1
  chart:
    git: https://github.com/openidl-aais/openidl-aais-gitops.git
    ref: carrier_dev
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.dev.carrier.internal.openidl.aaisdirect.com
      authpath: devcarrier-net-auth
      adminsecretprefix: carrier/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: carrier/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.ordererorg.dev.openidl.aaisdirect.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.3
      name: openidl-cc-default
      version: v10251448
      sequence: 1
      commitarguments: ''
      endorsementpolicies:  ''
      usecollectionconfig: false
    channel:
      name: defaultchannel
