apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-peer0
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-peer0
  chart:
    git: https://github.com/openidl-aais/openidl-aais-gitops.git
    ref: carrier_dev
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: carrier-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.carrier-net.carrier.dev.carrier.openidl.aaisdirect.com:8443
      gossipexternalendpoint: peer0.carrier-net.carrier.dev.carrier.openidl.aaisdirect.com:8443
      localmspid: carrierMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.3
      couchdb:
        username: carrier-user

    storage:
      peer:
        storageclassname: carriersc
        storagesize: 50Gi
      couchdb:
        storageclassname: carriersc
        storagesize: 50Gi

    vault:
      role: vault-role
      address: http://vault.dev.carrier.internal.openidl.aaisdirect.com
      authpath: devcarrier-net-auth
      secretprefix: carrier/crypto/peerOrganizations/carrier-net/peers/peer0.carrier-net
      secretambassador: carrier/crypto/peerOrganizations/carrier-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: carrier/credentials/carrier-net/couchdb/carrier?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: carrier.dev.carrier.openidl.aaisdirect.com
