access_id: ""
access_key: ""
region: ""
cluster_name: ""
account: ""
gitops_repo_url: "github.com/openidl-aais/openidl-aais-gitops"
gitops_repo_branch: "aais_dev"
gitops_repo_user: ""
gitops_repo_user_token: ""
gitops_repo_user_email: ""
ordererorg_domain: "openidl.aaisdirect.com"
domain: "openidl.aaisdirect.com"
internal_domain: "openidl.internal.aaisdirect.com"
env: "dev"
add_org: ""
registry: ""
chaincode_version: ""
node_type: "aais"

network:
    org_name: "aais"
    ordererorg: "true"
    ordererorg_name: "ordererorg"
    organizations:
        - name: "analytics"
          domain: "analytics.aaisdirect.com"
        - name: "carrier"
          domain: "carrier.openidl.aaisdirect.com"
        - name: "hig"
          domain: "carrier.hig1.aaisdirect.com"
        - name: "hig1"
          domain: "carrier.hig1.aaisdirect.com"
        - name: "caru"
          domain: "carrier.caru.aaisdirect.com"
        - name: "trv"
          domain: "trv.emergingtechdemo.com"
    channels:
        - name: defaultchannel
          chaincode:
              name: openidl-cc-default
              repo_url: github.com/openidl-org/openidl-main.git
              repo_branch: develop
              repo_path: openidl-chaincode/chaincode/openidl
        - name: anal-aais
          chaincode:
              name: openidl-cc-aais-carriers
              repo_url: github.com/openidl-org/openidl-main.git
              repo_branch: "develop"
              repo_path: openidl-chaincode/chaincode/openidl
              collectionconfig:
                - name: "analytics_aais_pdc"
                  policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
                - name: "anal_aais_pdc"
                  policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
        - name: anal-caru
        # chaincode details to be used to install and commit in the channel
          chaincode:
              # chaincode name
              name: openidl-cc-aais-carriers
              # github repo url from which the chaincode should be installed (public repository)
              repo_url: github.com/openidl-org/openidl-main.git
              # github repo branch from which the chaincode should be picked
              repo_branch: "develop"
              # chaincode directory path in the github repo 
              repo_path: openidl-chaincode/chaincode/openidl
              # private data collection to be used while approving an committing the chaincode
              collectionconfig:
                # name of the private data collection
                - name: "analytics_caru_pdc"
                  # policy to be used in private data collection
                  policy: "OR('analyticsMSP.member', 'caruMSP.member')"

