access_id: ""
access_key: ""
region: "us-east-1"
cluster_name: ""
account: ""
gitops_repo_url: "github.com/openidl-aais/openidl-aais-gitops.git"
gitops_repo_branch: "carrier_dev"
gitops_repo_user: ""
gitops_repo_user_token: ""
gitops_repo_user_email: ""
ordererorg_domain: "openidl.aaisdirect.com"
domain: "carrier.aaisdirect.com"
internal_domain: "carrier.internal.aaisdirect.com"
env: "dev"
add_org: ""
registry: ""
chaincode_version: ""
node_type: "carrier"

network:
    org_name: "carrier"
    ordererorg: "false"
    ordererorg_name: "ordererorg"
    organizations:
        - name: "analytics"
          domain: ""
          org_status: ""
        - name: "carrier"
          domain: ""
          org_status: ""
    channels:
         - name: analytics-carrier
           chaincode:
             name: openidl-cc-aais-carriers
             repo_url: github.com/openidl-org/openidl-main.git
             repo_branch: develop
             repo_path: openidl-chaincode/chaincode/openidl
             collectionconfig:
               name: "analytics_carrier_pdc"
               policy: "OR('analyticsMSP.member', 'carrierMSP.member')"
        - name: analytics-aais
          chaincode:
              name: openidl-cc-aais-carriers
              repo_url: github.com/openidl-org/openidl-main.git
              repo_branch: develop
              repo_path: openidl-chaincode/chaincode/openidl
              collectionconfig:
                  name: "analytics_aais_pdc"
                  policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
        - name: defaultchannel
          chaincode:
              name: openidl-cc-default
              repo_url: github.com/openidl-org/openidl-main.git
              repo_branch: develop
              repo_path: openidl-chaincode/chaincode/openidl
